/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sachini.trade.center;

import javax.swing.JFrame;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sandakelum
 */
public class service extends javax.swing.JFrame {

    int x = 0;
            int y = 0;
            int z = 0;
            int p = 0;
            int q = 0;
            int r = 0;
            int s = 0;
            int t = 0;
    public service() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        gosevtab();
        clock();
    }

    public ArrayList<sertab>dd(){
        ArrayList<sertab>dd =new ArrayList<>();
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
        java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sachini_trade_center","root","");
            String sevtab="SELECT * from servic";
            Statement st=con.createStatement();
            ResultSet show=st.executeQuery(sevtab);
            sertab sach;
            while (show.next()){
                sach=new sertab(show.getString("v_no"),show.getString("date"),show.getString("owner_name"),show.getInt("km"),show.getInt("eo"),show.getInt("go"),show.getInt("Do"),show.getInt("of"),show.getInt("af"),show.getInt("ff"),show.getInt("uc"),show.getInt("bw"));
                dd.add(sach);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return dd;
        
        
        
    }
    
    public void gosevtab(){
        
    ArrayList<sertab>list=dd();
    DefaultTableModel sevmod=(DefaultTableModel)sevtab.getModel();
    Object[] line=new Object[12];
        int k;
    for(k=0;k<list.size();k++){
        line[0]=list.get(k).getv_no();
        line[1]=list.get(k).getdate();
        line[2]=list.get(k).getowner_name();
        line[3]=list.get(k).getkm();
        line[4]=list.get(k).geteo();
        line[5]=list.get(k).getgo();
        line[6]=list.get(k).getDo();
        line[7]=list.get(k).getof();
        line[8]=list.get(k).getaf();
        line[9]=list.get(k).getff();
        line[10]=list.get(k).getuc();
        line[11]=list.get(k).getbw();
        sevmod.addRow(line);
    }
        
       
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        save = new javax.swing.JButton();
        vno = new javax.swing.JTextField();
        km = new javax.swing.JTextField();
        owner_name = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        eo = new javax.swing.JCheckBox();
        go = new javax.swing.JCheckBox();
        Do = new javax.swing.JCheckBox();
        of = new javax.swing.JCheckBox();
        af = new javax.swing.JCheckBox();
        ff = new javax.swing.JCheckBox();
        uc = new javax.swing.JCheckBox();
        bw = new javax.swing.JCheckBox();
        date = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sevtab = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        date1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sachini/trade/center/home.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1265, 30, 60, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SACHINI TRADE CENTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("V NO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Owner Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("KM");

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        vno.setToolTipText("pleace enter vehicle number with letter");
        vno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnoActionPerformed(evt);
            }
        });

        km.setToolTipText("only type integer number");
        km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmActionPerformed(evt);
            }
        });

        owner_name.setToolTipText("vehicle owner name");
        owner_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owner_nameActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("NEW SERVIC");
        jPanel2.add(jLabel10);

        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Engin Oil");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Gear Oil");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Deferancel Oil");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Oil Filter");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Air Filter");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Fual Filter");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Under Checup");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Body wash");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel5.add(eo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
        jPanel5.add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));
        jPanel5.add(Do, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));
        jPanel5.add(of, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        jPanel5.add(af, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));
        jPanel5.add(ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        jPanel5.add(uc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        jPanel5.add(bw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(owner_name)
                            .addComponent(km)
                            .addComponent(vno)
                            .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(owner_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(save)
                    .addComponent(delete))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 390, 580));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        sevtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "V_NO", "Date", "Owner Name", "KM", "E.O", "G.O", "D.O", "O.F", "A.F", "F.F", "U.checup", "B.Wash"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        sevtab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevtabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sevtab);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("SEARCH");

        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(193, 468, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 830, 580));

        date1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 204, 51));
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 190, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sachini/trade/center/,,.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new main().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sachini_trade_center","root","");

            int line=sevtab.getSelectedRow();
            String val=(sevtab.getModel().getValueAt(line,0).toString());

            String upd="UPDATE servic SET owner_name=?,km=?,eo=?,go=?,Do=?,of=?,af=?,ff=?,uc=?,bw=? WHERE v_no=? and date=?";
            PreparedStatement bvg = con.prepareStatement(upd);
            String vmod;
            String sd;

            
           bvg.setString(11, vno.getText());
            bvg.setString(12, date.getText());
            bvg.setString(1,owner_name.getText());
            bvg.setString(2,km.getText());
            if(eo.isSelected()){
               x=1; 
            }
            else{
                x=0;
            }
            
            bvg.setInt(3, x);
            if(go.isSelected()){
               y=1; 
            }
            else{
                y=0;
            }
            
            bvg.setInt(4, y);
            if(Do.isSelected()){
               z=1; 
            }
            else{
                z=0;
            }
            
            bvg.setInt(5, z);
            if(of.isSelected()){
               p=1; 
            }
            else{
                p=0;
            }
            
            bvg.setInt(6, p);
            if(af.isSelected()){
               q=1; 
            }else{
                q=0;
            }
            
            
            bvg.setInt(7, q);
            if(ff.isSelected()){
               r=1; 
            }
            else{
                r=0;
            }
            
            bvg.setInt(8, r);
            if(uc.isSelected()){
               s=1; 
            }
            else{
                s=0;
            }
            
            bvg.setInt(9, s);
            if(bw.isSelected()){
               t=1; 
            }
            else{
                t=0;
            }
            bvg.setInt(10, t);
           
            
            bvg.executeUpdate();

            JOptionPane.showMessageDialog(null,"success");
            

            vno.setText("");
            date.setText("");
            km.setText("");
            owner_name.setText("");
            eo.setSelected(false);
            go.setSelected(false);
            Do.setSelected(false);
            of.setSelected(false);
            af.setSelected(false);
            ff.setSelected(false);
            uc.setSelected(false);
            bw.setSelected(false);
            
            DefaultTableModel mod1=(DefaultTableModel)sevtab.getModel();
            mod1.setRowCount(0);
            gosevtab();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sachini_trade_center","root","");
            String partin = "insert into servic(v_no,date,owner_name,km,eo,go,do,of,af,ff,uc,bw )values(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement bvg = con.prepareStatement(partin);
           
            

            
            bvg.setString(1, vno.getText());
            bvg.setString(2, date.getText());
            bvg.setString(3,owner_name.getText());
            bvg.setString(4,km.getText());
            if(eo.isSelected()){
               x=1; 
            }
            
            bvg.setInt(5, x);
            if(go.isSelected()){
               y=1; 
            }
            
            bvg.setInt(6, y);
            if(Do.isSelected()){
               z=1; 
            }
            
            bvg.setInt(7, z);
            if(of.isSelected()){
               p=1; 
            }
            
            bvg.setInt(8, p);
            if(af.isSelected()){
               q=1; 
            }
            
            bvg.setInt(9, q);
            if(ff.isSelected()){
               r=1; 
            }
            
            bvg.setInt(10, r);
            if(uc.isSelected()){
               s=1; 
            }
            
            bvg.setInt(11, s);
            if(bw.isSelected()){
               t=1; 
            }
            bvg.setInt(12, t);
            bvg.executeUpdate();
            JOptionPane.showMessageDialog(null,"success");
            
            vno.setText("");
            date.setText("");
            km.setText("");
            owner_name.setText("");
            eo.setSelected(false);
            go.setSelected(false);
            Do.setSelected(false);
            of.setSelected(false);
            af.setSelected(false);
            ff.setSelected(false);
            uc.setSelected(false);
            bw.setSelected(false);
            
            DefaultTableModel mod1=(DefaultTableModel)sevtab.getModel();
            mod1.setRowCount(0);
            gosevtab();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_saveActionPerformed

    private void vnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnoActionPerformed

    private void kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmActionPerformed

    private void owner_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owner_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owner_nameActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int mas=JOptionPane.showConfirmDialog(null,"Are Your Shure.You Wan't Delete This", "DELETE", JOptionPane.YES_NO_OPTION);
        if(mas==0){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sachini_trade_center","root","");

            int line=sevtab.getSelectedRow();

            String upd="DELETE FROM servic WHERE v_no=? and date=?";
            PreparedStatement bvg = con.prepareStatement(upd);

            bvg.setString(1,vno.getText());
            bvg.setString(2,date.getText());

            bvg.executeUpdate();

            JOptionPane.showMessageDialog(null,"success");
            
            vno.setText("");
            date.setText("");
            km.setText("");
            owner_name.setText("");
            eo.setSelected(false);
            go.setSelected(false);
            Do.setSelected(false);
            of.setSelected(false);
            af.setSelected(false);
            ff.setSelected(false);
            uc.setSelected(false);
            bw.setSelected(false);
            DefaultTableModel mod1=(DefaultTableModel)sevtab.getModel();
            mod1.setRowCount(0);
            gosevtab();
    }//GEN-LAST:event_deleteActionPerformed
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }}
    private void sevtabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevtabMouseClicked
        int s=sevtab.getSelectedRow();
        TableModel mod=sevtab.getModel();
        vno.setText(mod.getValueAt(s,0).toString());
        date.setText(mod.getValueAt(s,1).toString());
        km.setText(mod.getValueAt(s,3).toString());
        owner_name.setText(mod.getValueAt(s,2).toString());
        String engin_oil=mod.getValueAt(s,4).toString();
        switch(engin_oil){
            case "1":
                eo.setSelected(true);
                break;
            default:
                eo.setSelected(false);
        }
        String gear_oil=mod.getValueAt(s,5).toString();
        switch(gear_oil){
            case "1":
                go.setSelected(true);
                break;
            default:
                go.setSelected(false);
        }
        String def_oil=mod.getValueAt(s,6).toString();
        switch(def_oil){
            case "1":
                Do.setSelected(true);
                break;
            default:
                Do.setSelected(false);
        }
        String oil_filter=mod.getValueAt(s,7).toString();
        switch(oil_filter){
            case "1":
                of.setSelected(true);
                break;
            default:
                of.setSelected(false);
        }
        String air_filter=mod.getValueAt(s,8).toString();
        switch(air_filter){
            case "1":
                af.setSelected(true);
                break;
            default:
                af.setSelected(false);
        }
        String fual_filter=mod.getValueAt(s,9).toString();
        switch(fual_filter){
            case "1":
                ff.setSelected(true);
                break;
            default:
                ff.setSelected(false);
        }
        String u_checup=mod.getValueAt(s,10).toString();
        switch(u_checup){
            case "1":
                uc.setSelected(true);
                break;
            default:
                uc.setSelected(false);
        }
        String b_wash=mod.getValueAt(s,11).toString();
        switch(b_wash){
            case "1":
                bw.setSelected(true);
                break;
            default:
                bw.setSelected(false);
        }
        
    }//GEN-LAST:event_sevtabMouseClicked

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
        DefaultTableModel mod1=(DefaultTableModel)sevtab.getModel();
        String src=search1.getText().toString();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(mod1);
        sevtab.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(src));
    }//GEN-LAST:event_search1KeyReleased

    
    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed
        
        /**
     * @param args the command line arguments
     */
    public void clock(){
        
        int f=0;
        new Thread(){
            public void run(){
                
                    Calendar cal = new GregorianCalendar();
                    
                    
                    int y = cal.get(Calendar.YEAR);
                    int mo = cal.get(Calendar.MONTH);
                    int da = cal.get(Calendar.DATE);
                    
                    
                    String datee= y+"."+mo+"."+da;
                    
                    
                    date1.setText(datee);
                
            }
        }.start();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new service().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Do;
    private javax.swing.JCheckBox af;
    private javax.swing.JCheckBox bw;
    private javax.swing.JTextField date;
    private javax.swing.JLabel date1;
    private javax.swing.JButton delete;
    private javax.swing.JCheckBox eo;
    private javax.swing.JCheckBox ff;
    private javax.swing.JCheckBox go;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField km;
    private javax.swing.JCheckBox of;
    private javax.swing.JTextField owner_name;
    private javax.swing.JButton save;
    private javax.swing.JTextField search1;
    private javax.swing.JTable sevtab;
    private javax.swing.JCheckBox uc;
    private javax.swing.JButton update;
    private javax.swing.JTextField vno;
    // End of variables declaration//GEN-END:variables
}
